image: "ruby:2.5"
stages:
 - patch
 - package

before_script:
  - apt-get update 
  - ruby -v                                   # Print out ruby version for debugging
  
Cinc-patch:
  stage: patch
  script:
    - apt-get -y install git build-essential
    - gem install omnibus
    - git clone --depth=1 https://github.com/chef/chef.git
    - cp -R cinc/* chef/
    - cd chef/omnibus

  artifacts:
    expire_in: 1d
    paths:
      - chef/
  
Cinc-package-deb:
  stage: package
  script:
    - cd chef/omnibus
    - bundle install
    - bundle exec omnibus build cinc
    - ls -alh */*
    - mv pkg/*.deb $CI_PROJECT_DIR
  artifacts:
    expire_in: 1mo
    paths:
      - ./*.deb